[workspace]
members = [
    "crates/notes-core",
    "crates/notes-storage-fs",
    "crates/notes-auth",
    "crates/notes-server-axum",
    "crates/notes-cli",
    "app/native",
]
default-members = [
    "crates/notes-core",
    "crates/notes-storage-fs",
    "crates/notes-auth",
    "crates/notes-server-axum",
    "crates/notes-cli",
]
resolver = "2"

[workspace.dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
