export enum RouteName {
  Home = 'home',
  Root = 'root',
  ServerVaults = 'server-vaults',
  ServerVault = 'server-vault',
  ServerNote = 'server-note',
  ServerVaultSettings = 'server-vault-settings',
  Search = 'search',
  Favorites = 'favorites',
  Drafts = 'drafts',
  Settings = 'settings',
  Vault = 'vault',
  Note = 'note',
  Teams = 'teams',
  Login = 'login',
  VaultSettings = 'vault-settings',
}
