export enum RouteName {
  Home = 'home',
  ServerRoot = 'server-root',
  ServerVault = 'server-vault',
  ServerNote = 'server-note',
  ServerVaultSettings = 'server-vault-settings',
  UserRoot = 'user-root',
  UserVault = 'user-vault',
  UserNote = 'user-note',
  UserVaultSettings = 'user-vault-settings',
  Search = 'search',
  Favorites = 'favorites',
  Feedback = 'feedback',
  FeedbackItem = 'feedback-item',
  Users = 'users',
  Settings = 'settings',
  Login = 'login',
  Setup = 'setup',
}
